BEGIN;

create table account
(
    id bigint not null,
    primary key (id)
);

create table balance
(
    id               bigint generated by default as identity,
    account_id       bigint,
    amount           decimal(19, 4),
    last_update_time timestamp,
    primary key (id)
);

INSERT INTO account(id)
VALUES (12345678);
INSERT INTO account(id)
VALUES (88888888);

INSERT INTO balance(id, account_id, amount, last_update_time)
VALUES (1, 12345678, 1000000, now());
INSERT INTO balance(id, account_id, amount, last_update_time)
VALUES (2, 88888888, 1000000, now());

COMMIT;