CREATE TABLE account
(
    id bigint not null,
    PRIMARY KEY (id)
);

CREATE TABLE balance
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id       BIGINT,
    amount           DECIMAL(19, 4),
    last_update_time TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_BALANCE_ACCOUNT_ID ON balance (account_id);

INSERT INTO account(id)
VALUES (12345678);
INSERT INTO account(id)
VALUES (88888888);

INSERT INTO balance(id, account_id, amount, last_update_time)
VALUES (1, 12345678, 1000000, now());
INSERT INTO balance(id, account_id, amount, last_update_time)
VALUES (2, 88888888, 1000000, now());